# Section 2.3

## Example 2.3.2

 `A \ b` $\quad\Leftrightarrow \quad \mathbf{A}^{-1} \mathbf{b}$ if $\mathbf{A}$ is square

In [ ]:
A = [1 0 -1; 2 2 1; -1 -3 0]

In [ ]:
b = [1, 2, 3]

In [ ]:
x = A \ b

In [ ]:
residual = b - A * x

In [ ]:
A = [0 1; 0 0]

In [ ]:
b = [1, -1]
x = A \ b    # throws an error

In [ ]:
rank(A)

## Example 2.3.3


### forward substitution (lower triangular)

In [1]:
A = rand(1.:9., 5, 5)

5×5 Matrix{Float64}:
 8.0  3.0  5.0  3.0  9.0
 7.0  3.0  8.0  4.0  3.0
 7.0  8.0  7.0  9.0  8.0
 6.0  2.0  3.0  4.0  6.0
 8.0  5.0  5.0  2.0  2.0

In [3]:
using LinearAlgebra
L = tril(A)

5×5 Matrix{Float64}:
 8.0  0.0  0.0  0.0  0.0
 7.0  3.0  0.0  0.0  0.0
 7.0  8.0  7.0  0.0  0.0
 6.0  2.0  3.0  4.0  0.0
 8.0  5.0  5.0  2.0  2.0

In [4]:
b = ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

solve $\mathbf{L} \mathbf{x} = \mathbf{b}$

In [5]:
using FNCFunctions
x = FNC.forwardsub(L, b)

5-element Vector{Float64}:
  0.125
  0.041666666666666664
 -0.02976190476190475
  0.06398809523809523
 -0.09375

residual:

In [6]:
b - L * x

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

### backward substitution (upper triangular)

In [7]:
α = 0.3
β = 2.2
U = diagm( 0=>ones(5), 1=>[-1, -1, -1, -1] )
U[1, [4, 5]] = [ α - β, β ]
U

5×5 Matrix{Float64}:
 1.0  -1.0   0.0  -1.9   2.2
 0.0   1.0  -1.0   0.0   0.0
 0.0   0.0   1.0  -1.0   0.0
 0.0   0.0   0.0   1.0  -1.0
 0.0   0.0   0.0   0.0   1.0

In [8]:
x_exact = ones(5)
b = [α, 0, 0, 0, 1]

5-element Vector{Float64}:
 0.3
 0.0
 0.0
 0.0
 1.0

In [9]:
x = FNC.backsub(U,b)
err = x - x_exact

5-element Vector{Float64}:
 2.220446049250313e-16
 0.0
 0.0
 0.0
 0.0

In [10]:
α = 0.3;
β = 1e12;
U = diagm( 0=>ones(5), 1=>[-1, -1, -1, -1] )
U[1, [4, 5]] = [ α - β, β ]

2-element Vector{Float64}:
 -9.999999999997e11
  1.0e12

In [11]:
x = FNC.backsub(U, b)
err = x - x_exact

5-element Vector{Float64}:
 -4.882812499995559e-5
  0.0
  0.0
  0.0
  0.0

In [12]:
U

5×5 Matrix{Float64}:
 1.0  -1.0   0.0  -1.0e12   1.0e12
 0.0   1.0  -1.0   0.0      0.0
 0.0   0.0   1.0  -1.0      0.0
 0.0   0.0   0.0   1.0     -1.0
 0.0   0.0   0.0   0.0      1.0