# Section 3.4

## Example 3.4.1

In [1]:
A = rand(float(1:9), 6, 4)
m,n = size(A)

(6, 4)

In [2]:
using LinearAlgebra
z = A[:, 1];
v = normalize(z - norm(z) * [1; zeros(m-1)])
P₁ = I - 2v * v'   # reflector

6×6 Matrix{Float64}:
 0.749269    0.0936586   0.468293   0.187317    0.187317    0.374634
 0.0936586   0.965015   -0.174927  -0.0699707  -0.0699707  -0.139941
 0.468293   -0.174927    0.125366  -0.349854   -0.349854   -0.699707
 0.187317   -0.0699707  -0.349854   0.860059   -0.139941   -0.279883
 0.187317   -0.0699707  -0.349854  -0.139941    0.860059   -0.279883
 0.374634   -0.139941   -0.699707  -0.279883   -0.279883    0.440234

New structural zeros:

In [3]:
P₁ * z

6-element Vector{Float64}:
 10.677078252031311
  1.1102230246251565e-16
  8.881784197001252e-16
  0.0
  0.0
  0.0

In [4]:
A = P₁ * A

6×4 Matrix{Float64}:
 10.6771        4.77659    6.64976  13.1122
  1.11022e-16   0.589288   2.88958   0.969756
  8.88178e-16  -4.05356   -6.5521   -7.15122
  0.0           0.178575  -2.22084   1.93951
  0.0           5.17858   -1.22084  -2.06049
  0.0          -4.64285   -1.44168  -4.12098

In [5]:
z = A[2:m, 2]
v = normalize(z - norm(z) * [1; zeros(m-2)])
P₂ = I - 2v * v'

5×5 Matrix{Float64}:
  0.0729888  -0.502072    0.0221182   0.641415  -0.57506
 -0.502072    0.728077    0.0119793   0.347392  -0.311454
  0.0221182   0.0119793   0.999472   -0.015304   0.0137208
  0.641415    0.347392   -0.015304    0.556194   0.397894
 -0.57506    -0.311454    0.0137208   0.397894   0.643268

In [6]:
A[2:m, :] = P₂ * A[2:m, :]
A

6×4 Matrix{Float64}:
 10.6771        4.77659       6.64976  13.1122
 -4.37826e-16   8.07367       3.4974    4.75229
  5.90921e-16   2.27502e-16  -6.2229   -5.10259
  1.30953e-17  -1.12485e-17  -2.23534   1.84926
  3.79757e-16  -5.99981e-16  -1.6414   -4.67769
 -3.40471e-16   3.06771e-16  -1.06463  -1.77453

In [7]:
for j in 3:n
    z = A[j:m, j]
    v = normalize(z - norm(z) * [1; zeros(m-j)])
    P = I - 2v * v'
    A[j:m, :] = P * A[j:m, :]
end

In [10]:
R = triu(A)

6×4 Matrix{Float64}:
 10.6771  4.77659  6.64976  13.1122
  0.0     8.07367  3.4974    4.75229
  0.0     0.0      6.89557   5.39279
  0.0     0.0      0.0       5.04021
  0.0     0.0      0.0       0.0
  0.0     0.0      0.0       0.0