# Section 2.2

## Example 2.2.1

### Matrix = 2D array

spaces for horizontal concatenation

semicolons / new lines for vertical concatenation

In [1]:
A = [ 1 2 3 4 5; 50 40 30 20 10
    π sqrt(2) exp(1) (1+sqrt(5))/2 log(3) ]

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

In [2]:
m, n = size(A)

(3, 5)

### Vector = 1D array

In [3]:
x = [ 3, 3, 0, 1, 0 ]
size(x)

(5,)

In [4]:
length(x)

5

In [5]:
y = [ 3 3 0 1 0 ]
size(y)

(1, 5)

In [6]:
y isa Vector

false

In [7]:
[3; 3; 0; 1; 0] isa Vector

true

### Building arrays

In [8]:
x

5-element Vector{Int64}:
 3
 3
 0
 1
 0

In [9]:
[ x  x ]

5×2 Matrix{Int64}:
 3  3
 3  3
 0  0
 1  1
 0  0

In [10]:
[ x; x ]

10-element Vector{Int64}:
 3
 3
 0
 1
 0
 3
 3
 0
 1
 0

 `zeros` and `ones` 

In [11]:
B = [ zeros(3, 2) ones(3, 1) ]

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  1.0
 0.0  0.0  1.0

`fill`

In [12]:
fill(67, 2, 4)

2×4 Matrix{Int64}:
 67  67  67  67
 67  67  67  67

`'` = adjoint = complex-conjugate transpose

In [13]:
A

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

In [14]:
A'

5×3 adjoint(::Matrix{Float64}) with eltype Float64:
 1.0  50.0  3.14159
 2.0  40.0  1.41421
 3.0  30.0  2.71828
 4.0  20.0  1.61803
 5.0  10.0  1.09861

In [15]:
x'

1×5 adjoint(::Vector{Int64}) with eltype Int64:
 3  3  0  1  0

### ranges

In [16]:
y = 1:4              # start:stop

1:4

In [17]:
z = 0:3:12           # start:step:stop

0:3:12

In [18]:
s = range(-1, 1, 5)

-1.0:0.5:1.0

### indexing

In [19]:
A

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

In [20]:
a = A[2, end-1]

20.0

In [21]:
x[2]

3

In [22]:
A[1:2, end-2:end]    # first two rows, last three columns

2×3 Matrix{Float64}:
  3.0   4.0   5.0
 30.0  20.0  10.0

In [23]:
A[:, 1:2:end]        # all of the odd columns

3×3 Matrix{Float64}:
  1.0       3.0       5.0
 50.0      30.0      10.0
  3.14159   2.71828   1.09861

### matrix algebra

In [24]:
using LinearAlgebra
B = diagm( [-1, 0, -5] )   # create a diagonal matrix

3×3 Matrix{Int64}:
 -1  0   0
  0  0   0
  0  0  -5

In [25]:
diagm(1 => [10, 20, 30])

4×4 Matrix{Int64}:
 0  10   0   0
 0   0  20   0
 0   0   0  30
 0   0   0   0

In [26]:
A

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

In [27]:
size(B), size(A)

((3, 3), (3, 5))

In [28]:
A + B    # throws an error

LoadError: DimensionMismatch: a has size (3, 5), b has size (3, 3), mismatch at dim 2

In [29]:
A + ones(size(A))

3×5 Matrix{Float64}:
  2.0       3.0       4.0       5.0       6.0
 51.0      41.0      31.0      21.0      11.0
  4.14159   2.41421   3.71828   2.61803   2.09861

In [30]:
BA = B * A     # matrix product

3×5 Matrix{Float64}:
  -1.0    -2.0       -3.0     -4.0      -5.0
   0.0     0.0        0.0      0.0       0.0
 -15.708  -7.07107  -13.5914  -8.09017  -5.49306

In [31]:
A * B    # throws an error

LoadError: DimensionMismatch: incompatible dimensions for matrix multiplication: tried to multiply a matrix of size (3, 5) with a matrix of size (3, 3). The second dimension of the first matrix: 5, does not match the first dimension of the second matrix: 3.

In [32]:
S = [3 0 2; 8 3 1; 3 3 8]

3×3 Matrix{Int64}:
 3  0  2
 8  3  1
 3  3  8

In [33]:
S^3    # same as S*S*S

3×3 Matrix{Int64}:
 159   84  212
 330  117  330
 654  318  731

In [34]:
C = -A

3×5 Matrix{Float64}:
  -1.0       -2.0       -3.0       -4.0       -5.0
 -50.0      -40.0      -30.0      -20.0      -10.0
  -3.14159   -1.41421   -2.71828   -1.61803   -1.09861

### elementwise / broadcast

In [35]:
A_C = A .* C

3×5 Matrix{Float64}:
    -1.0        -4.0    -9.0       -16.0       -25.0
 -2500.0     -1600.0  -900.0      -400.0      -100.0
    -9.8696     -2.0    -7.38906    -2.61803    -1.20695

In [36]:
x_to_two = x .^ 2

5-element Vector{Int64}:
 9
 9
 0
 1
 0

In [37]:
x² = x .^ 2

5-element Vector{Int64}:
 9
 9
 0
 1
 0

In [38]:
cos.(π * x)

5-element Vector{Float64}:
 -1.0
 -1.0
  1.0
 -1.0
  1.0

In [39]:
cospi.(x)

5-element Vector{Float64}:
 -1.0
 -1.0
  1.0
 -1.0
  1.0

# 