# Section 2.9

## Example 2.9.1

In [ ]:
using LinearAlgebra
A = diagm( 
    -1 => [4, 3, 2, 1, 0], 
    0 => [2, 2, 0, 2, 1, 2], 
    1 => fill(-1, 5) 
    )

In [ ]:
@show diag_main = diag(A);
@show diag_minusone = diag(A, -1);

In [ ]:
using FNCFunctions
L, U = FNC.lufact(A)
L

In [ ]:
U

In [ ]:
L, U = FNC.plufact(A)
L

## Example 2.9.2

In [1]:
A₁ = [  2     4     4     2.0
        4     5     8    -5
        4     8     6     2
        2    -5     2   -26   ]

4×4 Matrix{Float64}:
 2.0   4.0  4.0    2.0
 4.0   5.0  8.0   -5.0
 4.0   8.0  6.0    2.0
 2.0  -5.0  2.0  -26.0

In [2]:
using LinearAlgebra
L = LowerTriangular(diagm(ones(4)))

4×4 LowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅    ⋅ 
 0.0  1.0   ⋅    ⋅ 
 0.0  0.0  1.0   ⋅ 
 0.0  0.0  0.0  1.0

In [3]:
d = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [4]:
d[1] = A₁[1, 1]
L[:, 1] = A₁[:, 1] / d[1]
A₂ = A₁ - d[1] * L[:, 1] * L[:, 1]'

4×4 Matrix{Float64}:
 0.0   0.0   0.0    0.0
 0.0  -3.0   0.0   -9.0
 0.0   0.0  -2.0   -2.0
 0.0  -9.0  -2.0  -28.0

In [5]:
d[2] = A₂[2, 2]
L[:, 2] = A₂[:, 2] / d[2]
A₃ = A₂ - d[2] * L[:, 2] * L[:, 2]'

4×4 Matrix{Float64}:
 0.0  0.0   0.0   0.0
 0.0  0.0   0.0   0.0
 0.0  0.0  -2.0  -2.0
 0.0  0.0  -2.0  -1.0

In [6]:
d[3] = A₃[3, 3]
L[:, 3] = A₃[:, 3] / d[3]
A₄ = A₃ - d[3] * L[:, 3] * L[:, 3]'


4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0

In [7]:
d[4] = A₄[4, 4]
@show d;
L

d = [2.0, -3.0, -2.0, 1.0]


4×4 LowerTriangular{Float64, Matrix{Float64}}:
 1.0    ⋅    ⋅    ⋅ 
 2.0   1.0   ⋅    ⋅ 
 2.0  -0.0  1.0   ⋅ 
 1.0   3.0  1.0  1.0

In [8]:
opnorm(A₁ - (L * diagm(d) * L'))

0.0

## Example 2.9.3

In [9]:
A = rand(1.0:9.0, 4, 4)
B = A + A'

4×4 Matrix{Float64}:
 16.0  16.0   7.0  16.0
 16.0  16.0   6.0   9.0
  7.0   6.0   4.0  11.0
 16.0   9.0  11.0   2.0

$$(A + A^T)^T = A^T + (A^T)^T = A^T + A$$

In [10]:
using LinearAlgebra
cholesky(B)    # throws an error

LoadError: PosDefException: matrix is not positive definite; Factorization failed.

In [11]:
B = A' * A
cf = cholesky(B)

Cholesky{Float64, Matrix{Float64}}
U factor:
4×4 UpperTriangular{Float64, Matrix{Float64}}:
 13.3417  14.0912   8.39475   6.82074
   ⋅       3.38204  0.504981  5.58469
   ⋅        ⋅       3.04517   2.6013
   ⋅        ⋅        ⋅        3.08578

In [12]:
R = cf.U

4×4 UpperTriangular{Float64, Matrix{Float64}}:
 13.3417  14.0912   8.39475   6.82074
   ⋅       3.38204  0.504981  5.58469
   ⋅        ⋅       3.04517   2.6013
   ⋅        ⋅        ⋅        3.08578

In [13]:
opnorm(R' * R - B) / opnorm(B)

0.0