# Section 2.6



## Example 2.6.1


In [ ]:
using FNCFunctions

In [ ]:
A = [2 0 4 3 ; -4 5 -7 -10 ; 1 15 2 -4.5 ; -2 0 2 -13];
L, U = FNC.lufact(A)
L

In [ ]:
A[[2, 4], :] = A[[4, 2], :]  
L, U = FNC.lufact(A)
L

In [ ]:
U[1, :] = A[1, :]
L[:, 1] = A[:, 1] / U[1, 1]
A -= L[:, 1] * U[1, :]'


## Example 2.6.2

In [ ]:
A₁ = [2 0 4 3 ; -2 0 2 -13; 1 15 2 -4.5 ; -4 5 -7 -10]

In [ ]:
L, U = zeros(4,4), zeros(4,4)

In [ ]:
i = argmax( abs.(A₁[:, 1]) ) 

In [ ]:
U[1, :] = A₁[i, :]
L[:, 1] = A₁[:, 1] / U[1, 1]
A₂ = A₁ - L[:, 1] * U[1, :]'

In [ ]:
i = argmax( abs.(A₂[:, 2]) ) 

In [ ]:
U[2, :] = A₂[i, :]
L[:, 2] = A₂[:, 2] / U[2, 2]
A₃ = A₂ - L[:, 2] * U[2, :]'

In [ ]:
@show i = argmax( abs.(A₃[:, 3]) ) 
U[3, :] = A₃[i, :]
L[:, 3] = A₃[:, 3] / U[3, 3]
A₄ = A₃ - L[:, 3] * U[3, :]'

In [ ]:
@show i = argmax( abs.(A₄[:, 4]) ) 
U[4, :] = A₄[i, :]
L[:, 4] = A₄[:, 4] / U[4, 4];

In [ ]:
A₁ - L * U

In [ ]:
U

In [ ]:
L

In [ ]:
L[[4,3,2,1], :]

## Example 2.6.3

In [ ]:
A = [2 0 4 3 ; -2 0 2 -13; 1 15 2 -4.5 ; -4 5 -7 -10]

In [ ]:
using FNCFunctions
B = A[[4, 3, 2, 1], :]
L, U = FNC.lufact(B);

In [ ]:
U

In [ ]:
L

## Example 2.6.4

In [ ]:
using FNCFunctions
A = rand(1:20, 4, 4)
L, U, p = FNC.plufact(A)
A[p, :] - L * U   # should be ≈ 0

In [ ]:
b = rand(4)
z = FNC.forwardsub(L, b[p])
x = FNC.backsub(U, z)

In [ ]:
b - A*x

## Example 2.6.5

In [ ]:
A = randn(500, 500)    # 500x500 with normal random entries
A \ rand(500)          # force compilation for timing
@elapsed for k=1:50; A \ rand(500); end

In [ ]:
using LinearAlgebra
factored = lu(A)       # store factorization result
factored \ rand(500)   # force compilation for timing
@elapsed for k=1:50; factored \ rand(500); end

## Example 2.6.6

In [1]:
ϵ = 1e-12
A = [-ϵ 1; 1 -1]
b = A * [1, 1]

2-element Vector{Float64}:
 0.999999999999
 0.0

In [2]:
using FNCFunctions
L, U = FNC.lufact(A)
x = FNC.backsub( U, FNC.forwardsub(L, b) )

2-element Vector{Float64}:
 0.9999778782798785
 1.0

In [3]:
L, U, p = FNC.plufact(A)
x = FNC.backsub( U, FNC.forwardsub(L, b[p]) )

2-element Vector{Float64}:
 1.0
 1.0

In [4]:
ϵ = 1e-20; A = [-ϵ 1; 1 -1]
b = A * [1, 1]
L, U = FNC.lufact(A)
x = FNC.backsub( U, FNC.forwardsub(L, b) )

2-element Vector{Float64}:
 -0.0
  1.0

┌ Error: Error watching manifest
│   exception =
│    TOML Parser error:
│    /Users/driscoll/Documents/GitHub/fnc/Manifest.toml:4:15 error: key already has a value
│      julia_version = "1.12.6"
│                    ^          
│    Stacktrace:
│     [1] parse
│       @ ./toml_parser.jl:445 [inlined]
│     [2] get_updated_dict(p::Base.TOML.Parser{nothing}, f::Base.CachedTOMLDict)
│       @ Base ./loading.jl:247
│     [3] (::Base.var"#parsed_toml##0#parsed_toml##1"{String, Base.TOMLCache{nothing}})()
│       @ Base ./loading.jl:291
│     [4] lock(f::Base.var"#parsed_toml##0#parsed_toml##1"{String, Base.TOMLCache{nothing}}, l::ReentrantLock)
│       @ Base ./lock.jl:335
│     [5] parsed_toml
│       @ ./loading.jl:278 [inlined]
│     [6] parsed_toml
│       @ ./loading.jl:276 [inlined]
│     [7] manifest_paths!(pkgpaths::Dict{Base.PkgId, String}, manifest_file::String)
│       @ Revise ~/.julia/packages/Revise/HiWo5/src/pkgs.jl:418
└ @ Revise ~/.julia/packages/Revise/HiWo5/src/pkgs.jl:

In [ ]:
A \ b