# Section 3.4

## Example 3.4.1

In [1]:
A = rand(float(1:9), 6, 4)

6×4 Matrix{Float64}:
 8.0  9.0  4.0  9.0
 5.0  6.0  7.0  2.0
 7.0  7.0  5.0  3.0
 8.0  9.0  8.0  8.0
 7.0  7.0  8.0  6.0
 2.0  5.0  5.0  2.0

In [2]:
m, n = size(A)
using LinearAlgebra
z = A[:, 1];
v = normalize(z - norm(z) * [1; zeros(m-1)])

6-element Vector{Float64}:
 -0.4995100435085767
  0.31341926915349255
  0.43878697681488954
  0.5014708306455881
  0.43878697681488954
  0.12536770766139702

In [3]:
P₁ = I - 2v * v'   # reflector

6×6 Matrix{Float64}:
 0.500979   0.313112    0.438357   0.500979   0.438357   0.125245
 0.313112   0.803537   -0.275049  -0.314341  -0.275049  -0.0785853
 0.438357  -0.275049    0.614932  -0.440078  -0.385068  -0.110019
 0.500979  -0.314341   -0.440078   0.497054  -0.440078  -0.125736
 0.438357  -0.275049   -0.385068  -0.440078   0.614932  -0.110019
 0.125245  -0.0785853  -0.110019  -0.125736  -0.110019   0.968566

In [4]:
P₁ * P₁

6×6 Matrix{Float64}:
  1.0           5.36008e-17   3.89582e-17  …   6.67138e-17  -4.22406e-18
  5.36008e-17   1.0          -1.03552e-17     -1.03552e-17  -2.10951e-18
  3.89582e-17  -1.03552e-17   1.0             -1.80083e-17  -1.39683e-17
 -4.8162e-17    9.8532e-18   -4.10207e-17     -4.10207e-17  -3.35574e-17
  6.67138e-17  -1.03552e-17  -1.80083e-17      1.0          -9.05137e-20
 -4.22406e-18  -2.10951e-18  -1.39683e-17  …  -9.05137e-20   1.0

New structural zeros:

In [5]:
P₁ * z

6-element Vector{Float64}:
 15.968719422671311
  2.7755575615628914e-17
  2.7755575615628914e-16
 -1.1102230246251565e-15
  2.7755575615628914e-16
  0.0

In [6]:
A = P₁ * A

6×4 Matrix{Float64}:
 15.9687       17.6595    14.5284    13.3386
  2.77556e-17   0.566552   0.393918  -0.722255
  2.77556e-16  -0.606828  -4.24852   -0.811157
 -1.11022e-15   0.306483  -2.56973    3.64439
  2.77556e-16  -0.606828  -1.24852    2.18884
  0.0           2.82662    2.35757    0.911098

In [7]:
z = A[2:m, 2]
v = normalize(z - norm(z) * [1; zeros(m-2)])
P₂ = I - 2v * v'

5×5 Matrix{Float64}:
  0.187387  -0.200708    0.101369   -0.200708    0.934903
 -0.200708   0.950427    0.0250372  -0.0495729   0.230912
  0.101369   0.0250372   0.987355    0.0250372  -0.116624
 -0.200708  -0.0495729   0.0250372   0.950427    0.230912
  0.934903   0.230912   -0.116624    0.230912   -0.0755955

In [8]:
A[2:m, :] = P₂ * A[2:m, :]
A

6×4 Matrix{Float64}:
 15.9687       17.6595       14.5284    13.3386
 -2.18756e-16   3.02344       3.12072    0.809363
  2.1667e-16    6.45581e-17  -3.57502   -0.432862
 -1.07947e-15  -2.37718e-17  -2.90988    3.45333
  2.1667e-16    9.11958e-17  -0.575022   2.56714
  2.83609e-16   6.40195e-17  -0.779586  -0.851012

In [9]:
for j in 3:n
    z = A[j:m, j]
    v = normalize(z - norm(z) * [1; zeros(m-j)])
    P = I - 2v * v'
    A[j:m, :] = P * A[j:m, :]
end

In [10]:
R = triu(A)

6×4 Matrix{Float64}:
 15.9687  17.6595   14.5284   13.3386
  0.0      3.02344   3.12072   0.809363
  0.0      0.0       4.71027  -1.97739
  0.0      0.0       0.0       3.93919
  0.0      0.0       0.0       0.0
  0.0      0.0       0.0       0.0