# Section 4.5

## Example 4.5.3


$$
\begin{split}
    f_1(x_1,x_2,x_3) &= e^{x_2 - x_1} - 2 \\
    f_2(x_1,x_2,x_3) &= x_1x_2 + x_3\\
    f_3(x_1,x_2,x_3) &= x_2x_3 + x_1^2 - x_2
\end{split}
$$

$$
    \mathbf{J}(x) =
    \begin{bmatrix}
       -e^{x_2 - x_1} & e^{x_2 - x_1} & 0\\
      x_2 & x_1 & 1\\
       2x_1 & x_3-1 & x_2
    \end{bmatrix}.
$$


In [ ]:
function func(x)
    return [exp(x[2] - x[1]) - 2,
        x[1] * x[2] + x[3],
        x[2] * x[3] + x[1]^2 - x[2]
    ]
end;

function jac(x)
    J = zeros(3, 3)
    J[:, 1] = [-exp(x[2] - x[1]), x[2], 2x[1]]
    J[:, 2] = [ exp(x[2] - x[1]), x[1], x[3] - 1]
    J[:, 3] = [0, 1, x[2]]
    return J
end;

In [35]:
x = [-1, 2, 3]
δ = 1e-5
(func(x + δ*[0, 0, 1]) - func(x)) / δ

3-element Vector{Float64}:
 0.0
 1.0000000000065512
 2.0000000000131024

In [33]:
jac(x)

3×3 Matrix{Float64}:
 -20.0855  20.0855  0.0
   2.0     -1.0     1.0
  -2.0      2.0     2.0

In [36]:
using FNCFunctions

x₁ = [0, 0, 0]
ϵ = eps()
x = FNC.newtonsys(func, jac, x₁, xtol=ϵ, ftol=ϵ);

In [37]:
x

7-element Vector{Vector{Float64}}:
 [0.0, 0.0, 0.0]
 [-1.0, 0.0, 0.0]
 [-0.578586294114295, 0.1571725882285898, 0.1571725882285898]
 [-0.4631386148886986, 0.23090368503021674, 0.11545249687009654]
 [-0.45802686753214106, 0.23512071352763037, 0.10771316029325663]
 [-0.4580332807487811, 0.23511389981124436, 0.10768999092388233]
 [-0.45803328064126886, 0.23511389991867646, 0.10768999090411432]

In [38]:
func(x[end])

3-element Vector{Float64}:
  0.0
 -1.3877787807814457e-17
  0.0

In [39]:
using LinearAlgebra

x₁ = BigFloat.([0, 0, 0])
ϵ = eps(BigFloat)
x = FNC.newtonsys(func, jac, x₁, xtol=ϵ, ftol=ϵ);
r = x[end]
residual = norm(func(r))

2.413882494292164487214410894417828565903424680443304778914633123377914826618847e-78

In [40]:
using PrettyTables

logerr = [Float64(log(norm(r - x[k]))) for k in 1:length(x)-1]
ratios = [NaN; [logerr[i+1] / logerr[i] for i in 1:length(logerr)-1]]

pretty_table( (iter=eachindex(logerr), logerr, ratios);
    column_labels=["iteration", "log error", "ratio"], backend=:html )

iteration,log error,ratio
1,-0.642465,NaN
2,-0.509988,0.793799
3,-1.88491,3.69598
4,-4.58533,2.43266
5,-10.5971,2.31109
6,-22.5988,2.13254
7,-45.8704,2.02977
8,-84.0624,1.83261
9,-122.096,1.45244
10,-160.132,1.31152
