# Section 2.4

## Example 2.4.2

$$
\mathbf{A}\mathbf{B} = \sum_{k=1}^n \mathbf{a}_k \mathbf{b}_k^T = (\mathbf{a}_1 \mathbf{b}_1^T) + (\mathbf{a}_2 \mathbf{b}_2^T) + \cdots + (\mathbf{a}_n \mathbf{b}_n^T)
$$

In [ ]:
using LinearAlgebra
L = tril( rand(1:9, 3, 3) )

In [ ]:
U = triu( rand(1:9, 3, 3) )

In [ ]:
L[:, 1], U[1, :]

In [ ]:
L[:, 1] * U[1, :]'

In [ ]:
L[:, 2], U[2, :]

In [ ]:
L[:, 2] * U[2, :]'

In [ ]:
L[:, 3], U[3, :]

In [ ]:
L[:, 3] * U[3, :]'

In [ ]:
sum(L[:, k] * U[k, :]' for k in 1:3)

In [ ]:
L * U

## Example 2.4.3

In [1]:
using LinearAlgebra

A₁ = [
     2    0    4     3 
    -4    5   -7   -10 
     1   15    2   -4.5
    -2    0    2   -13
    ];

In [2]:
L = diagm(ones(4))

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [3]:
U = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

$\mathbf{A}_1 = \boldsymbol{\ell}_1\mathbf{u}_1^T + \boldsymbol{\ell}_2\mathbf{u}_2^T + \boldsymbol{\ell}_3\mathbf{u}_3^T + \boldsymbol{\ell}_4\mathbf{u}_4^T$

In [4]:
U[1, :] = A₁[1, :]
U

4×4 Matrix{Float64}:
 2.0  0.0  4.0  3.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [5]:
L[:, 1] = A₁[:, 1] / U[1, 1]
L

4×4 Matrix{Float64}:
  1.0  0.0  0.0  0.0
 -2.0  1.0  0.0  0.0
  0.5  0.0  1.0  0.0
 -1.0  0.0  0.0  1.0

In [6]:
A₂ = A₁ - L[:, 1] * U[1, :]'

4×4 Matrix{Float64}:
 0.0   0.0  0.0    0.0
 0.0   5.0  1.0   -4.0
 0.0  15.0  0.0   -6.0
 0.0   0.0  6.0  -10.0

$\mathbf{A}_2 = \boldsymbol{\ell}_2\mathbf{u}_2^T + \boldsymbol{\ell}_3\mathbf{u}_3^T + \boldsymbol{\ell}_4\mathbf{u}_4^T$ 

In [7]:
U[2, :] = A₂[2, :]
U

4×4 Matrix{Float64}:
 2.0  0.0  4.0   3.0
 0.0  5.0  1.0  -4.0
 0.0  0.0  0.0   0.0
 0.0  0.0  0.0   0.0

In [8]:
L[:, 2] = A₂[:, 2] / U[2, 2]
L

4×4 Matrix{Float64}:
  1.0  0.0  0.0  0.0
 -2.0  1.0  0.0  0.0
  0.5  3.0  1.0  0.0
 -1.0  0.0  0.0  1.0

In [9]:
A₃ = A₂ - L[:, 2] * U[2, :]'

4×4 Matrix{Float64}:
 0.0  0.0   0.0    0.0
 0.0  0.0   0.0    0.0
 0.0  0.0  -3.0    6.0
 0.0  0.0   6.0  -10.0

Now we can deal with the lower right $2\times 2$ submatrix of the remainder in a similar fashion.

In [10]:
U[3, :] = A₃[3, :]
L[:, 3] = A₃[:, 3] / U[3, 3]
A₄ = A₃ - L[:, 3] * U[3, :]'

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  2.0

Finally, we pick up the last unknown in the factors.

In [11]:
U[4, 4] = A₄[4, 4];

In [12]:
L

4×4 Matrix{Float64}:
  1.0  0.0  -0.0  0.0
 -2.0  1.0  -0.0  0.0
  0.5  3.0   1.0  0.0
 -1.0  0.0  -2.0  1.0

In [13]:
U

4×4 Matrix{Float64}:
 2.0  0.0   4.0   3.0
 0.0  5.0   1.0  -4.0
 0.0  0.0  -3.0   6.0
 0.0  0.0   0.0   2.0

Backward error:

In [14]:
A₁ - L * U

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

## Example 2.4.4

In [1]:
A = [2 0 4 3; -4 5 -7 -10; 1 15 2 -4.5; -2 0 2 -13];
b = [4, 9, 9, 4];

In [2]:
A

4×4 Matrix{Float64}:
  2.0   0.0   4.0    3.0
 -4.0   5.0  -7.0  -10.0
  1.0  15.0   2.0   -4.5
 -2.0   0.0   2.0  -13.0

In [3]:
b

4-element Vector{Int64}:
 4
 9
 9
 4

In [4]:
using FNCFunctions
L, U = FNC.lufact(A);

$$
\begin{aligned}
\mathbf{A} \mathbf{x} &= \mathbf{b} \\ 
(\mathbf{L} \mathbf{U}) \mathbf{x} &= \mathbf{b}\\
\mathbf{L} (\mathbf{U} \mathbf{x}) &= \mathbf{b} \\
\mathbf{U} \mathbf{x} = \mathbf{z} \quad & \mathrm{ and } \quad \mathbf{L} \mathbf{z} = \mathbf{b}
\end{aligned}
$$


In [5]:
z = FNC.forwardsub(L, b)
x = FNC.backsub(U, z);

In [6]:
b - A*x

4-element Vector{Float64}:
  0.0
 -5.684341886080802e-14
  2.842170943040401e-14
  0.0